'use strict';
const fs=require('fs'),path=require('path'),zlib=require('zlib');const root=__dirname,dist=path.join(root,'dist'),out=path.join(root,'release');fs.mkdirSync(out,{recursive:true});
const files=JSON.parse(fs.readFileSync(path.join(root,'content/page-index.json'))),pages=Object.fromEntries(files.map(p=>[p,fs.readFileSync(path.join(dist,p),'utf8')]));
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.relative(dist,path.join(p,e.name)).split(path.sep).join('/')]);
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon','.txt':'text/plain; charset=utf-8','.xml':'application/xml; charset=utf-8'};
const assets={},previewAssets={};for(const file of walk(dist)){const bytes=fs.readFileSync(path.join(dist,file)),type=types[path.extname(file)]||'application/octet-stream',encoding=/^(text\/|application\/xml|image\/svg)/.test(type)?'utf8':'base64';assets['/'+file]={type,body:bytes.toString(encoding),encoding};if(file.startsWith('assets/'))previewAssets[file]='data:'+type+';base64,'+bytes.toString('base64');}
const counts=JSON.parse(fs.readFileSync(path.join(root,'content/site-counts.json'))),health=JSON.stringify({status:'ok',...counts});
const archive=zlib.gzipSync(Buffer.from(JSON.stringify(assets)),{level:9}).toString('base64');
const code=`// MoreSpace Services: self-contained Railway Bun website.\nimport {gunzipSync,gzipSync} from 'node:zlib';\nconst assets=JSON.parse(gunzipSync(Buffer.from('${archive}','base64')).toString('utf8'));const cache=new Map();\nconsole.log('MoreSpace v3 ready: ${files.length} pages, ${Object.keys(assets).length} assets');\nBun.serve({port:Number(Bun.env.PORT||3000),fetch(req){if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405,headers:{Allow:'GET, HEAD'}});let p;try{p=decodeURIComponent(new URL(req.url).pathname)}catch{return new Response('Invalid path',{status:400})}if(p==='/health')return new Response(req.method==='HEAD'?null:${JSON.stringify(health)},{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});if(p==='/')p='/index.html';const a=assets[p];if(!a)return new Response('Not found',{status:404,headers:{'Content-Type':'text/plain; charset=utf-8'}});if(!cache.has(p))cache.set(p,gzipSync(Buffer.from(a.body,a.encoding)));return new Response(req.method==='HEAD'?null:cache.get(p),{headers:{'Content-Type':a.type,'Content-Encoding':'gzip','Cache-Control':'public, max-age=300','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'"}})}});\n`;
fs.writeFileSync(path.join(root,'railway-function.ts'),code);
const safe=s=>s.replace(/<\/script/gi,'<\\/script'),css=fs.readFileSync(path.join(dist,'site.css'),'utf8'),js=fs.readFileSync(path.join(dist,'site.js'),'utf8'),metrics=fs.readFileSync(path.join(dist,'metrics.js'),'utf8');
const router=String.raw`(function(){'use strict';var pages=window.MoreSpacePreviewPages;function parse(){var raw=location.hash.slice(1);if(raw[0]==='/')raw=raw.slice(1);if(!raw)raw='index.html';try{var u=new URL(raw,'https://morespace.preview/');return{path:u.pathname.slice(1),search:u.search,anchor:u.hash}}catch{return{path:'index.html',search:'',anchor:''}}}function hash(r){return '#/'+r.path+r.search+r.anchor}window.MoreSpacePreviewResolveAsset=function(raw){var r=window.MoreSpacePreviewRoute||{path:'index.html'};try{return window.MoreSpacePreviewAssets[new URL(raw,'https://morespace.preview/'+r.path).pathname.slice(1)]||raw}catch{return raw}};window.MoreSpacePreviewUpdateQuery=function(v){var r=window.MoreSpacePreviewRoute,p=new URLSearchParams(r.search);Object.keys(v).forEach(k=>v[k]?p.set(k,v[k]):p.delete(k));r.search=p.toString()?'?'+p.toString():'';history.replaceState(null,'',hash(r))};function render(){var r=parse(),html=pages[r.path];if(!html){r={path:'index.html',search:'',anchor:''};html=pages[r.path];history.replaceState(null,'',hash(r))}window.MoreSpacePreviewRoute=r;var d=new DOMParser().parseFromString(html,'text/html');document.title=d.title+' — Preview';document.body.innerHTML=d.body.innerHTML;document.querySelectorAll('img[src]').forEach(img=>img.src=window.MoreSpacePreviewResolveAsset(img.getAttribute('src')));window.dispatchEvent(new Event('morespace:pagechange'));if(r.anchor){var t=document.getElementById(decodeURIComponent(r.anchor.slice(1)));if(t)t.scrollIntoView()}else window.scrollTo(0,0)}document.addEventListener('click',function(e){if(e.defaultPrevented||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;var a=e.target.closest('a[href]');if(!a||a.hasAttribute('download')||a.target==='_blank')return;var raw=a.getAttribute('href');if(!raw||/^(https?:|mailto:|tel:|data:|blob:)/i.test(raw))return;var c=window.MoreSpacePreviewRoute,u=new URL(raw,'https://morespace.preview/'+c.path+c.search),r={path:u.pathname.slice(1),search:u.search,anchor:u.hash};if(!pages[r.path])return;e.preventDefault();if(hash(r)===location.hash)render();else location.hash=hash(r)});window.addEventListener('hashchange',render);render()})();`;
let preview=pages['index.html'].replace(/<link rel="stylesheet" href="site\.css">/,'<style>'+css+'</style>').replace(/<script defer src="metrics\.js"><\/script><script defer src="site\.js"><\/script>/,'').replace('href="favicon.svg"','href="data:image/svg+xml;base64,'+fs.readFileSync(path.join(dist,'favicon.svg')).toString('base64')+'"');
preview=preview.replace('</body>',()=>'<script>window.MoreSpacePreviewPages='+JSON.stringify(pages).replace(/</g,'\\u003c')+';</script><script>window.MoreSpacePreviewAssets='+JSON.stringify(previewAssets)+';</script><script>'+safe(metrics)+'</script><script>'+safe(js)+'</script><script>'+router+'</script></body>');
fs.writeFileSync(path.join(out,'morespace-multipage-preview.html'),preview);fs.writeFileSync(path.join(root,'content/build-summary.json'),JSON.stringify({...counts,assets:Object.keys(assets).length,embeddedLogos:Object.keys(previewAssets).length,previewBytes:Buffer.byteLength(preview),functionBytes:Buffer.byteLength(code)},null,2));console.log(JSON.parse(fs.readFileSync(path.join(root,'content/build-summary.json'))));
